# Generated by Django 5.1.6 on 2025-02-15 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_usertype_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 13, 13, 20, 426285, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(default='upcoming'),
        ),
    ]
