# Generated by Django 5.1.6 on 2025-02-15 14:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_post_event_date_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 14, 53, 8, 552979, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='a.post'),
        ),
    ]
